### ISSUE TITLE
DepthwiseConvlution layer in tensorrt

### ISSUE THREAD

**Issue by VigorPoppy** [eric612/TensorRT-Yolov3-model#1]
Hi, depthwise layer is not supported in TRT and I thought there are two ways:
1、I tried to replace all depthwise layer with conv layer(group convlution), bu the behaviors between these two kinds of layers is different. so just replace the depthwise layer with conv layers in a trained model works, but the mAP decreased, too. I thought it may caused by the replacement. I should train the model with conv layer( group version).
2、add depthwise layer as plugin layer in TRT.

**Comment by eric612** [comment]
Thanks for your feedback , if you want train group convolution in caffe , it is recommend enable cudnn that I already upload a new code . It would be faster than original caffe implementation.
